services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: api
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    container_name: worker
    depends_on:
      - api
    links:
      - api
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api
    networks:
      - backend

networks:
  backend:
    driver: bridge
